version: "3"
services:
    weather:
        build:
            context: .
            dockerfile: Dockerfile
        command: bash deploy.sh
        network_mode: "host"
        ports:
            - '6969:6969'
