name: Docker Build and Push
on:
  push:
    branches: [ main, staging ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Docker image tag
      id: set-tag
      run: |
        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
          echo "IMAGE_TAG=latest" >> $GITHUB_OUTPUT
        elif [ "${{ github.ref }}" = "refs/heads/staging" ]; then
          echo "IMAGE_TAG=staging" >> $GITHUB_OUTPUT
        fi

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/wgetweather:${{ steps.set-tag.outputs.IMAGE_TAG }}
          ghcr.io/${{ github.repository_owner }}/wgetweather:${{ github.sha }}